os-net-config/os-net-config

os_net_config/impl_nmstate.py
The below rules having route table names ``alternate`` can't be given to nmstate templates as a string. Instead it needs to be converted to a integer based on the map available at ``/etc/iproute2/rt_tables``.
- rule: "iif eno2 table alternate"
- rule: "from 10.0.2.0/24 table alternate"
=> Support IP Rules with route_table names

zuul.d/projects.yaml
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1800
=> Fix file regex for zuul job

os_net_config/impl_nmstate.py, os_net_config/sriov_config.py, os_net_config/tests/test_impl_ifcfg.py, os_net_config/tests/test_sriov_config.py
Re-factoring the configure_switchdev function
to disable the tc hw offload flag for legacy mode
=> Re-factor switchdev for HWOL flag

os_net_config/common.py, os_net_config/impl_ifcfg.py, os_net_config/impl_nmstate.py, os_net_config/tests/test_impl_nmstate.py
Update ovs_extra to set the MAC table limit
for OvSBridge in nm provider
=> Add ovs_extra param for mac table size

etc/os-net-config/samples/dcb_day2_sample.yaml, os_net_config/common.py, os_net_config/dcb_config.py, os_net_config/objects.py, os_net_config/schema.yaml
Modified the day2 configuration templates for dcb config where the ``name`` is replaced with ``device``
=> DCB config schema update

os_net_config/impl_nmstate.py, os_net_config/tests/test_impl_nmstate.py
Force reset the numvfs configuration for regular interfaces.
=> Reset the numvfs for ethernet interface in nmstate provider

os_net_config/dcb_config.py
Editing some debugs of DCB for easy interpretation of logs
=> Editing some debugs of DCB for easy interpretation of logs

requirements.txt
Depends-On: https://github.com/os-net-config/os-net-config/pull/52
=> Pin setuptools

os_net_config/impl_nmstate.py
During the reapply of nmstate templates, the mismatch in routes and route rules will result in deletion of some routes and route rules. The deletion of some of the routes conflicts with the addition of new entries. In order to avoid the conflict, when there is a difference between the existing route/route rules and the desired ones, the existing routes and route rules were flushed and the new entries were made.
Linked Jira: https://issues.redhat.com/browse/OSPRH-9904
=> Fix errors in deleting routes and route rules

os_net_config/impl_nmstate.py
The initial settings are preserved and reapplied in case of failures in applying the nmstate provider.
=> Rollback to the initial settings in case of failure

os_net_config/tests/test_impl_nmstate.py
Reverts os-net-config/os-net-config#75
=> Revert "Add stubs for show_running_config() to fix linter jobs"

os_net_config/tests/test_impl_nmstate.py
(cherry picked from commit 15e54ccef83f8fbf3dc6e0fa71f005191dc9a96e)
Signed-off-by: Karthik Sundaravel <ksundara@redhat.com>
=> Add stubs for show_running_config() to fix linter jobs

os_net_config/cli.py
On some environment, libnmstate is too old and we cannot upgrade it. However, it shouldn't prevent from running os-net-config with the ifcfg provider.
Only import impl_nmstate if the requested provider actually is nmstate. If there is a missing module, an explicit error will be raised.
(cherry picked from commit 6dffeea98d0999ab509043f1bec524ad5bc9aeac)
=> providers: lazily load NetConfig implementations

os_net_config/cli.py
When the environment has the libnmstate support available with a minimum desired version, the default provider shall be set to nmstate
=> Set the default provider as nmstate

os_net_config/impl_nmstate.py, os_net_config/tests/test_impl_nmstate.py
Handle the below ovs_extra settings for dpdk ports/bonds
- set port dpdkbond0 bond_mode=balance-slb
- set port dpdkbond1 bond_updelay=1000
- set port dpdkbond1 other_config:bond-detect-mode=miimon
- set port dpdkbond1 other_config:bond-miimon-interval=100
- set Interface dpdk0 options:n_rxq_desc=2048
- set Interface dpdk0 options:n_txq_desc=2048
=> Handle ovs-extra for ovs dpdk ports and bonds

os_net_config/cli.py
=> Fix missing f-string in rollback log

os_net_config/impl_ifcfg.py, os_net_config/tests/test_impl_ifcfg.py
Reverts os-net-config/os-net-config#96, need to have --force
=> Revert "Change DNS without restarting interface"

os_net_config/impl_ifcfg.py
This change allows DNS servers and search domains to be modified on the fly without restarting interfaces. The DNS nameservers and search domains are written to the ifcfg file and /etc/resolv.conf will be updated in place.
This change also includes some code cleanup and updates string formatting in some places to match Python3 style.
Link: https://bugzilla.redhat.com/2315341
Fixes: https://issues.redhat.com/browse/OSP-32857
Fixes: https://issues.redhat.com/browse/OSP-32858
Signed-off-by: Dan Sneddon <dsneddon@redhat.com>
=> ifcfg-dns: Allow DNS changes without restarting

etc/os-net-config/samples/linux_bond.yaml, os_net_config/impl_nmstate.py
add all linux bond options supported by nmstate
=> Add linux bond supported options

os_net_config/impl_nmstate.py
Add the docstrings and comments to the nmstate provider implementation.
=> nmstate: add the docstring and comments

.github/workflows/ci.yml, CONTRIBUTING.rst, README.rst, check-commits
Recently, there were multiple occasions where the git commits were not following the expected standards. Add a github action that will check every commit in all pull requests.
=> ci: add script to check git commits

os_net_config/__init__.py, os_net_config/cli.py, os_net_config/common.py, os_net_config/dcb_config.py, os_net_config/impl_eni.py, os_net_config/impl_ifcfg.py, os_net_config/impl_nmstate.py, os_net_config/objects.py, os_net_config/sriov_bind_config.py, os_net_config/sriov_config.py, os_net_config/tests/test_utils.py, os_net_config/utils.py
The logging in nmstate provider is printing the data structures in json format which is not easy to read and decipher. These data structures are printed in yaml format for the ease of reading. Also some of the logs are repeated at several levels leading to duplication of the logging. These issues are addressed here.
=> logs: Make logging precise and readable

os_net_config/impl_nmstate.py
The desired and the current states of the devices are compared for PFs and VFs. The desired state is applied only when there is a change in configuration. A ticket is opened in nmstate to perform the comparison of the states and apply it when needed. JIRA: https://issues.redhat.com/browse/RHEL-67120
(cherry picked from commit 5bc677adf1e695bf2566adb55bb9bc3a5cbd76cc)
=> sriov: Apply the PF/VF config only when there is a change

.gitignore, README.rst, bindep.txt, setup.cfg
doc: update readme description
This commit is to update readme content related to os-net-config repo
* Correct reference to invalid urls
* Added more description for os-net-config feature
Closes: https://issues.redhat.com/browse/osprh-8784
=> update README and doc content

os_net_config/impl_nmstate.py
In NIC partitioning scenario with only dpdk ports, the VF configuration is skipped since add_sriov_vf() will not be called for dpdk ports. The VF configuration for dpdk ports that uses NIC partitioning are added to the sriov_vf_data.
=> sriov: nic partitioning with only dpdk ports fail

os_net_config/cli.py
Cuurent implementation of adding objects is dublicating adding objects that have sriov_pf members.
The patch refactors check_configure_sriov to check if the object itself or any of its tree members are sriov_pf so adding that object will happen once
Fixes: https://issues.redhat.com/browse/OSPCIX-702
Closes-Bug: #2020100
Change-Id: I3895a5200bc97a294a8b5774c24972f1f58b40bf (cherry picked from commit 7996a2e79e607aed3036bf3a851bde318ff0fef7)
=> Refactor check_configure_sriov to prevent dublicate adding sriov_pfs

os_net_config/impl_ifcfg.py, os_net_config/tests/test_impl_ifcfg.py
When checking diff of DPDKBond data, the interfaces can be in any order. No of elements only matter
=> bond: ignore order for dpdkbond

os_net_config/impl_nmstate.py, os_net_config/tests/test_impl_nmstate.py
Certain ethtool opts like `-U`, `--set-priv-flags` are not yet supported by nmstate schema. Such ethtool opts are configured via NetworkManager-dispatcher scripts which directly calls the ethtool command when the device state changes to `up`.
=> nmstate: use dispatcher scripts to configure unhandled ethtool opts

os_net_config/utils.py
The path /sys/class/net/{pf_name}/device/virtfn{vfid}/net/{vf_name} will be available when the default VF driver is bound with the VF. When sriov_drivers_autoprobe=0, the drivers will not be bound with VF by default and hence the path will not be available. In NIC partitioning use cases, the driver will be bound by os-net-config. It is necessary to wait for the above path to be available in order to read the VF name. Few retries are made to check for the existence of the vf_path.
=> sriov: wait for completion of driver binding

os_net_config/sriov_config.py
When os-net-config-sriov is run eg. during upgrade/update, setting PF config like autoprobe fails. Adding udev check to wait for the PF creation
Fixes: https://issues.redhat.com/browse/OSPRH-15126
=> sriov: exception seen in sriov_config service

os_net_config/sriov_config.py
When os-net-config-sriov is run eg. during uprade/update, setting of PF config like autoprobe fails. Adding udev check to wait for the PF creation
Closes: https://issues.redhat.com/browse/OSPRH-15126
(cherry picked from commit 217a3f02ccd9e49b2c03bb03ca0ac8060360faa9)
=> sriov: intermittent exception seen in sriov_config service

os_net_config/sriov_config.py
As a follow-up review comment for PR199 and PR206, updating log messages
- sriov_config.py:327:53: E272 multiple spaces before keyword
- sriov_config.py:588:17: E127 continuation line over-indented for visual indent
- Added log info on udev wait success
=> log: follow-up patch

os_net_config/impl_ifcfg.py
Changes are done to make a note of real nics during cleanup and restore the ifcfg and bring up the interface after cleanup.
Closes: https://issues.redhat.com/browse/OSPRH-17306
=> ifcfg: Avoid bringing down of physical interfaces during cleanup

os_net_config/impl_nmstate.py, os_net_config/tests/test_impl_nmstate.py
Adding support to handle the ovs_extra fields for ovs bonds, dpdk bonds
=> nmstate: handle ovs_extra for ovs bonds

os_net_config/impl_nmstate.py, os_net_config/tests/test_impl_nmstate.py
Changes:
- Enhanced parse_ovs_extra_for_iface() to track unhandled commands
- Modified _ovs_extra_cfg_eq_val() to return match/mismatch counts
- Added validation in add_interface() and add_sriov_vf() functions
- Consolidated external-ids regex patterns for consistency
- Added clear error messages for debugging invalid commands
- Unit tests generated using AI (cursor/claude-4-sonnet), manually reviewed and adapted
Assisted-by: cursor/claude-4-sonnet
(cherry picked from commit 3acdd697cd7066ee8549787ff20c57abab320817)
=> nmstate: implement error handling for ovs_extra for interfaces

os_net_config/objects.py, os_net_config/tests/test_cli.py, os_net_config/tests/test_impl_eni.py, os_net_config/tests/test_utils.py, os_net_config/utils.py
To avoid silent failure when user sets mtu more than device allowed mtu, added checks to fail on such cases
Closes: https://issues.redhat.com/browse/OSPRH-17600
=> mtu: check for device maxmtu

os_net_config/tests/test_utils.py, os_net_config/utils.py
* Add retry logic with 2-second delays for transient failures
* Simplify return codes to 0 (success) or 1 (error)
* Handle both stderr and ProcessExecutionError paths consistently
* Add comprehensive test coverage for all error scenarios
=> utils: refactor DPDK detach with retry mechanism and error handler

os_net_config/tests/test_utils.py, os_net_config/utils.py
Allow DPDK interface removal by either name or PCI address. Log all removal actions and delete the mapping file when empty.
=> utils: improve DPDK device cleanup and mapping file management

os_net_config/common.py
Fixed minor typo and logging name instead of ifname as that is more useful.
=> common: fix typo and improve logging in get_pci_address function

os_net_config/impl_nmstate.py, os_net_config/tests/test_impl_nmstate.py
This patch implements comprehensive error detection and validation for ovs_extra bridge configurations, providing clear error messages for unsupported commands while maintaining full backward compatibility. This is patch 4 of a multi-patch series focused on OVS bridge ovs_extra enhancements.
This completes the bridge-focused portion of the ovs_extra enhancement series. Future patches will address DPDK and bond related ovs_extra configurations.
Assisted-by: cursor/claude-4-sonnet
=> nmstate: implement error handling for ovs_extra bridge configurations

os_net_config/__init__.py, os_net_config/cli.py, os_net_config/objects.py, os_net_config/tests/test_cli.py
- check is remove_config data is present
- if yes, validate and apply it before the network_config data is applied
- Added UT for the same
Fixes: https://issues.redhat.com/browse/OSPRH-18113
=> rm_config: apply the remove_config section of config YAML

os_net_config/impl_ifcfg.py
Implement device management detection for the ifcfg provider to identify which network devices are under its control. This enables proper cleanup and configuration management across different device types.    
Key changes:
- is_device_managed() method with intelligent device detection
- identify provider for OVS devices (bridges, bonds, ports) with type validation
- identify dpdk port/bonds with PCI address mapping and bond membership
- identify SR-IOV VF detection with DPDK port correlation
- Add RemoveDeviceIfcfgData class for structured device information
- Validate NetworkManager control via UUID and NM_CONTROLLED checks
- Optimize performance with likely-filename-first search strategy
This enhancement enables accurate provider selection and prevents configuration conflicts between …
=> rm_config: identify if device is managed by ifcfg provider

doc/source/usage.rst
The usage.rst shall be modified to indicate the exit code when detailed exit codes are enabled
=> doc: update the doc for the exit codes
