- os_net_config/objects.py
When sriov PF map is updated from LinuxBond, it does not update the link_mode and vdpa for the member PF interface
Change-Id: I6564cba495c81760907258058afe411574dc2582 (cherry picked from commit 4deb7a817139fe6982a3f8c78aadba64fc49edc5)
> Link_mode and vdpa is not updated in sriov_map

- os_net_config/cli.py
Cuurent implementation of adding objects is dublicating adding objects that have sriov_pf members.
The patch refactors check_configure_sriov to check if the object itself or any of its tree members are sriov_pf so adding that object will happen once
Closes-Bug: #2020100
Change-Id: I3895a5200bc97a294a8b5774c24972f1f58b40bf (cherry picked from commit 7996a2e79e607aed3036bf3a851bde318ff0fef7) (cherry picked from commit 770e41df3c27390a97f581f7f926511362888297)
> Refactor check_configure_sriov to prevent dublicate adding sriov_pfs

- os_net_config/__init__.py
- os_net_config/impl_ifcfg.py
- os_net_config/objects.py
- zuul.d/layout.yaml
The ovs command to set the primary interface of the bond fails when the interface is not active. This patch ignores the error and proceeds with the remaining configuration.
Change-Id: I3592af4f357dca483fc7914133e1fc248d12f11a (cherry picked from commit b4779a6b28e01689025919548ee3ef51c13c8188) (cherry picked from commit 01d1c57596aa0e61f04fbd4008cc43505f06246c)
> Skip failure on setting inactive interface as bond's primary

- os_net_config/impl_ifcfg.py
Consider the case where 2 interfaces eno1 and eno2 are added as members to linux bond bond1. And vlan100 is created on bond1.  Now when os-net-config is re-run it finds a change in ifcfg-eno1 or ifcfg-eno2. In this case the affected devices would be restarted, which triggers a restart of bond1. In this case the vlan devices associated with the bond shall also be restarted.
Change-Id: If80544262bf3827e5af0c32abcdcc5b6c2e71905 (cherry picked from commit ba37f85889a949b953c53c1085439c49028e3487)
> VLANs needs to be restarted when the associated linux bond is restarted

- os_net_config/impl_nmstate.py
Change-Id: Ib6678112bd9b3c4db4c97d517635d64121460cab
> Fix add_ovs_interface log which mislead ovs dpdk port

- etc/os-net-config/samples/dcb_config_sample.yaml
- etc/os-net-config/samples/dcb_sample.yaml
- os_net_config/cli.py
- os_net_config/common.py
- os_net_config/dcb_config.py
- os_net_config/dcb_netlink.py
- os_net_config/objects.py
- os_net_config/schema.yaml
- os_net_config/tests/test_sriov_bind_config.py
- os_net_config/tests/test_sriov_config.py
- os_net_config/tests/test_utils.py
- os_net_config/utils.py
- requirements.txt
- setup.cfg
Support dscp configuration using os-net-config templates. It uses pyroute2 modules to send/receive, encode/decode the netlink messages. The persistence of the configuration is done with dcb_config.service
> Adding support for DSCP configuration

- os_net_config/impl_nmstate.py
- os_net_config/objects.py
The primary hw address of the bridge needs to be set on the OVS interface attached to the bridge instead of the bridge.
> Set the primary hw address for ovs bridge

- os_net_config/impl_ifcfg.py
- os_net_config/impl_nmstate.py
- os_net_config/tests/test_cli.py
- os_net_config/tests/test_objects.py
The stub for update_sriov_pf_map is defined for many test cases in test_objects.py. Reduced the redefinition of the same
> Reduce the definition of test stubs for update_sriov_pf_map

- os_net_config/impl_nmstate.py
With nmstate as provider, the existing routes are removed when the table-id or metric is not provided by the user. Added checks to skip removing the routes and re-adding them.
> Mismatch in table-id, metric shall be ignored for routes

- os_net_config/impl_nmstate.py
With nmstate provider, during the cleanup operation, avoid bringing down interface which are not managed by NM. The states of these devices cannot be modified by NM and hence avoiding the cleanup and reconfiguration of the same.
> Avoid bringing down devices not managed by NM

- etc/os-net-config/samples/vdpa.json
- etc/os-net-config/samples/vdpa.yaml
- os_net_config/objects.py
- os_net_config/schema.yaml
- os_net_config/sriov_config.py
- os_net_config/tests/test_impl_ifcfg.py
This patch adds an option to configure multi queue for vDPA devices.
Change-Id: I0cf4b4296d784835d0164c81e7a910e975efcd34
> Add Multi-Queue support for vDPA devices

- zuul.d/projects.yaml
openstack-services-content-provider will build the os-net-config rpm from the os-net-config pr proposed under test.
Then same rpm will be consumed in the edpm job via gating repo. This will allow to test os-net-config changes with the edpm job.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1800
> Add EDPM Zuul Jobs for os-net-config repo

- os_net_config/dcb_config.py
When Day 2 configuration is applied the DCB config service is not getting started. Because of this after reboot the dscp2prio mapping is not persistent after reboot.
Failure logs are as below.
[cloud-admin@rhos-nfv-10 ~]$ sudo os-net-config-dcb --show
2024-06-19 14:02:59.127 INFO os_net_config.show -----------------------------
2024-06-19 14:02:59.127 INFO os_net_config.show Interface: enp4s0f0np0
2024-06-19 14:02:59.127 INFO os_net_config.show DCBX Mode : FW Controlled
2024-06-19 14:02:59.127 INFO os_net_config.show Trust mode: dscp
2024-06-19 14:02:59.127 INFO os_net_config.show dscp2prio mapping: prio:4 dscp:34 prio:5 dscp:40
2024-06-19 14:02:59.127 INFO os_net_config.show tc: 0 , tsa: vendor, priority:  1
2024-06-19 14:02:59.128 INFO os_net_config.show tc: 1 , tsa: vendor, priority: …
> Need to start DCB config service after Day 2 config is applied

- os_net_config/dcb_config.py
With Day 2 configuration, the dcb logs are not printed in the log file. Setting the required flag enables the logging.
The DCB related logs are not coming in file /var/log/os-net-config.log after DCB config applied through Day 2 configuration. 
After applying the changes in the commit, can see the DCB logs in the log file (/var/log/os-net-config.log)
> Enable dcb logs to print in log file

- os_net_config/dcb_config.py
If for the same priority the protocol is changed in Day2 operations , it results in Key error.  While parsing the AppTable, the missing keys are also referenced which leads to the key error.
> Fix key error in DCB configuration

- os_net_config/impl_nmstate.py
In case of NIC partitioning the VF parameters are not configured due to the incorrect updation of apply_data dict. The VF parameters are applied separately now.
> VF parameters are configured with nmstate provider

- os_net_config/objects.py
As part of deployment templates the nic numbering
is being used and for DCB configs it is not supported and expecting physical interface naming. Hence adding changes to use the mapping of the nics to appropriate interfaces for DCB configs, so that it can support with nic numbering.
Changes are done and tested as below. Logs shared for reference.
[cloud-admin@rhos-nfv-10 ~]$ sudo os-net-config -d 
2024-07-17 10:32:13.094 INFO os_net_config.main Using config file at: /etc/os-net-config/config.yaml
2024-07-17 10:32:13.095 INFO os_net_config.impl_ifcfg.__init__ Ifcfg net config provider created.
2024-07-17 10:32:13.095 INFO os_net_config.main Using mapping file at: /etc/os-net-config/mapping.yaml
2024-07-17 10:32:13.096 DEBUG os_net_config.main interface_mapping: {'nic1': 'e4:43:4b:4d:ec:64', …
> Handle nic mapping for DCB configs

- os_net_config/sriov_config.py
- os_net_config/tests/test_sriov_config.py
On boot, sriov_config.service runs in parallel with the probing of PCI devices. There is no synchronization point that we can use to run the service *after* all PCI devices have been probed. This leads to the service failing depending on the time it takes for devices to be probed:
```
12:31:30 os-net-config-sriov[1772]: FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/net/ens2f0np0/device/sriov_numvfs'
...
12:31:43 kernel: mlx5_core 0000:17:00.0 ens2f0np0: renamed from eth0
```
The issue is that there is no UDEV rule to back this up when using NIC partitioning.
Add an explicit call to udevadm wait before trying to access the files. If the devices have already been probed, it will not cause any delay. On the other hand, if the devices haven't been probed yet or if the …
> sriov_config: fix race condition on boot

- os_net_config/sriov_config.py
By default, udevadm wait has no timeout. If the `-t`, `--timeout` option is not specified, the command will wait for the device to be initialized forever. Here's an excerpt from `udevadm(8)`:
```
udevadm wait [options] [device|syspath] ...
Wait for devices or device symlinks being created and initialized
by systemd-udevd.
-t, --timeout=SECONDS
Maximum number of seconds to wait for the specified devices or
device symlinks being created, initialized, or removed. The
default value is "infinity".
^^^^^^^^
```
If there is a misconfiguration or a hardware issue, this can lead to stalling on boot.
Add an explicit 60 seconds timeout after which the command will fail with an explicit error:
```
Timed out for waiting devices being initialized.
```
> sriov_config: give up on waiting for pf after 60 seconds

- os_net_config/impl_nmstate.py
- os_net_config/tests/test_impl_nmstate.py
The default values of the VF parameters like Trust, Spoofcheck, Promisc are updated for OvS and OvS user bridges, Linux bonds. This update is not effectively applied on the nmstate provider's sriov_vf_data, leading to inconsistency between the sriov map and the VF configurations applied. Now the update of the default values are applied on sriov_vf_data.
> Update the VF args for OvS / OvS user bridges

- zuul.d/projects.yaml
The py39 and pep8 jobs were previously removed due to limited CI resources and now adding them back to ensure compliance in validation.
> Adding pep8 and  py39 jobs back to CI

- zuul.d/projects.yaml
https://review.rdoproject.org/r/c/config/+/53945 limit the job inclusion from ci-framework main and proposed-18 branch.
openstack-services-content-provider's parent *cifmw-tcib-base* defined in ci-framework. ci-framework repo has main branch. os-net-config has master branch. The zuul is not able run the job *openstack-services-content-provider* due to branch difference and giving following error:
```
Unable to freeze job graph: Job podified-multinode-edpm-deployment-crc depends on openstack-services-content-provider which was not run.
``` 
Setting override-checkout to main and tells the zuul to use proper branch and run the job. Hence, it  fixes the issue.
Signed-off-by: Chandan Kumar <raukadah@gmail.com>
> Add override-checkout main to the content provider job

- os_net_config/impl_nmstate.py
- os_net_config/tests/test_impl_nmstate.py
The default values of the VF parameters like Trust, Spoofcheck, Promisc are updated for OvS and OvS user bridges, Linux bonds. This update is not effectively applied on the nmstate provider's sriov_vf_data, leading to inconsistency between the sriov map and the VF configurations applied. Now the update of the default values are applied on sriov_vf_data.
Depends-On: https://github.com/os-net-config/os-net-config/pull/40
> Update the VF args for OvS / OvS user bridges for nmstate provider

- os_net_config/cli.py
- os_net_config/schema.yaml
- os_net_config/tests/test_validator.py
Since there is a limitation from OvS for minimum 2 members required for dpdkbond members, updating
the schema to allow only 2 ports.
Set default failure for schema errors.
Added negative test cases for the same.
> Update schema for dpdkbond members

- os_net_config/__init__.py
- os_net_config/common.py
- os_net_config/dcb_config.py
- os_net_config/sriov_config.py
- os_net_config/tests/test_impl_eni.py
- os_net_config/tests/test_impl_ifcfg.py
Allow `os-net-config-sriov` and `os-net-config-dcb` logs to be stored in the default log file. Also the exception logs shall be stored in the default log file.
Depends-On: https://github.com/os-net-config/os-net-config/pull/46
> Exception logging shall also be stored in default log file

- os_net_config/impl_nmstate.py
- os_net_config/tests/test_impl_nmstate.py
- os_net_config/utils.py
Reads the maximum number of VFs supported by the NIC and validates the support for SR-IOV, and the required numvfs. Its found that configuring TOTAL_VFS on a virtual NIC could not be configured and verified by nmstate. Hence the validation is added here.
> Validate SR-IOV support before configuring it

- etc/os-net-config/samples/vdpa.json
- etc/os-net-config/samples/vdpa.yaml
- os_net_config/objects.py
- os_net_config/schema.yaml
- os_net_config/sriov_config.py
- os_net_config/tests/test_impl_ifcfg.py
This patch adds an option to configure multi queue for vDPA devices.
Change-Id: I0cf4b4296d784835d0164c81e7a910e975efcd34 (cherry picked from commit 384f46f8e0dfb847ab543e82f8cd08f5065edceb)
> Add Multi-Queue support for vDPA devices (#7)

- os_net_config/impl_nmstate.py
- os_net_config/tests/test_impl_nmstate.py
Force reset the numvfs configuration for regular interfaces.
(cherry picked from commit 9af352a64cc2c84ac71e7cd7dc6a9ca61a0e0fe4)
Signed-off-by: Karthik Sundaravel <ksundara@redhat.com>
> Reset the numvfs for ethernet interface in nmstate provider

- os_net_config/__init__.py
- os_net_config/cli.py
- os_net_config/impl_ifcfg.py
- os_net_config/impl_nmstate.py
In cases where migration of provider fails, the network configurations shall be rolled back to the previous provider.
Depends-On: https://github.com/os-net-config/os-net-config/pull/54
> Roll back to previous provider incase of migration failure

- os_net_config/impl_nmstate.py
- os_net_config/tests/test_impl_nmstate.py
Switchdev and vDPA are not supported yet with nmstate provider. ConfigurationError exception is raised when these features are used with nmstate provider.
> Raise exception when switchdev/vDPA is enabled with nmstate provider

- os_net_config/cli.py
- os_net_config/objects.py
DCB relies on pyroute2 0.7 which isn't available everywhere. When the configuration does not require DCB, do not import the dcb_* related code to avoid any import errors.
(cherry picked from commit d2991f48b8722d1b438a1a355bc69d72669f6527)
> dcb: lazily import module

- os_net_config/cli.py
When the provider fails to configure the network, it reports an appropriate exception. The exception is handled so that the migration cases like rollback is supported, but the exception needs to be raised for non migration cases.
> Report failure when provider fails to configure network

- os_net_config/tests/test_impl_nmstate.py
Some of the stubs are repeated for some of the tests in test_impl_nmstate.py. These stubs are moved to the setUp() of the respective class, so that the stub implementation is not repetitive.
> Move stubs that are repeated several times

- os_net_config/objects.py
- os_net_config/schema.yaml
For the DCB configurations over a dpdkbond, currently the configs needs to be repeated under all the dpdk bond members (interfaces). This patch adds support in os-net-config to be able to apply DCB configurations directly under the object of type ovs dpdk bond.
> DCB configurations over OVS DPDK BOND

- os_net_config/cli.py
There are use cases where we don't want to enforce the schema validation, like the current ovn-bgp-agent OpenStack deployments where we rely on "empty" bridges:
- type: ovs_bridge
name: br-ex
use_dhcp: false
- type: ovs_bridge
name: br-vlan
use_dhcp: false
It is left to the agent/kernel to set up routing and send traffic to the right nic(s).
This commit restore the previous behavior, where we emit a warning and continue.
It is left to the application/user to pass the --exit-on-validation-errors option at runtime if required.
> Do not fail on schema validation errors

- os_net_config/impl_ifcfg.py
- os_net_config/tests/test_impl_ifcfg.py
With this change the DNS servers and search domains can be changed in place without restarting the interface when using ifcfg provider. This change also does some code cleanup for readability and updates the string handling to be more Python3 compliant in some places.
> Change DNS without restarting interface

- os_net_config/schema.yaml
- os_net_config/tests/test_validator.py
Instead of allowing schema error (PR#100), updating schema for ovs_bridge to allow empty members:
There are use cases where we don't want to enforce the schema validation, like the current ovn-bgp-agent OpenStack deployments where we rely on "empty" bridges:
type: ovs_bridge
name: br-ex
use_dhcp: false
type: ovs_bridge
name: br-vlan
use_dhcp: false
It is left to the agent/kernel to set up routing and send traffic to the right nic.
Added test case for same
Fixes issue: https://bugzilla.redhat.com/show_bug.cgi?id=2316090
> Allow empty members for ovs_bridge

- os_net_config/cli.py
- os_net_config/common.py
- os_net_config/impl_ifcfg.py
- os_net_config/impl_nmstate.py
- os_net_config/objects.py
- os_net_config/utils.py
When os-net-config is run with noop, its failing due to permission issues or trying to write files and configure devices. When `noop` is used, there shall be no changes made to the machine, while the configuration files or templates derived shall be output on the console. This is done so that the template/compatibility issues of the config.yaml could be validated on a given hardware without changing the system files or configuration.
>  noop: Run os-net-config without applying the changes

- os_net_config/impl_ifcfg.py
When trying to create a Linux Bridge with something like
```
- type: linux_bridge
name: br-ex
mtu: 1500
use_dhcp: false
dns_servers: ['192.168.140.80']
domain: ['ctlplane.example.com', 'internalapi.example.com', 'storage.example.com', 'tenant.example.com']
addresses:
- ip_netmask: 192.168.140.100/24
routes: [{'destination': '0.0.0.0/0', 'nexthop': '192.168.140.1'}]
```
We get and exception saying that `route6_path` variable was used before assignment.
That happens because the variable is actually called `br_route6_path`, and this patch fixes this.
> ifcfg: Fix linux bridge

- os_net_config/impl_ifcfg.py
- os_net_config/tests/test_impl_ifcfg.py
The ovs_extra field of ovs_dpdk_bond is duplicated in the ifcfg files. The duplicate entries are prevented from modifying the ifcfg files.
> ifcfg: Remove duplicate ovs_extra for DPDK bond

- os_net_config/sriov_config.py
When sriov_config service is run after updating the os-net-config
package in an existing deployment, we get the error “KeyError:
‘drivers_autoprobe’“. This is due to the previously configured
sriov_config.yaml which does not have the `drivers_autoprobe` field.
Adding a check for the existence of the ’drivers_autoprobe` field to
avoid the error
> avoid KeyError: 'drivers_autoprobe' when use os-net-config-sriov

- os_net_config/sriov_config.py
In RHEL8.4 the `udevadm wait` is not supported. The command is run so as to wait for the sysfs to be ready for configuring sriov_numvfs. So when `udevadm wait fails`, an attempt is made using `udevadm settle` to wait for the udev events.
> udevadm: handle udevadm wait on RHEL8.4

- os_net_config/impl_nmstate.py
- os_net_config/tests/test_impl_nmstate.py
The ovs internal interface is named as {bridge_name}-p earlier. The name is changed to {bridge_name} now so that it is consistent with the ifcfg provider.
> ovs: keep the ovs internal interface name same as the bridge

- os_net_config/impl_nmstate.py
currently os-net-config fail to rerun in case config.json not includes sriov VF definitions (or sriov been defined on the host without nmstate ) the fail reason is the desire VFs hard coded to zero is not as current.
this pr will replace the zero with current defined VFs to avoid the fail verification.
> ignore VFs defined 

- os_net_config/impl_nmstate.py
- os_net_config/schema.yaml
- os_net_config/tests/test_impl_nmstate.py
nmstate support to add route to interface through local device ( ip r add default dev ). 
Not defining next-hop-address is equal to next-hop-address: 0.0.0.0
> adding the option to add route though next-hop-interface

- os_net_config/common.py
When running 'os-net-config -i' getting below error ERROR os_net_config.objects.mapped_nics mac
f8:f2:1e:03:a5:c2 not found in available nics
Fixing the path of the appropriate interface.
> bond: fix to match the mac address with appropriate interface

- os_net_config/cli.py
(cherry picked from commit 2676e9b89347b4ffbb32981eb919598ca5000c0e)
> fix missing f-string in rollback log

- os_net_config/cli.py
- os_net_config/common.py
- os_net_config/impl_ifcfg.py
- os_net_config/impl_nmstate.py
- os_net_config/objects.py
- os_net_config/utils.py
When os-net-config is run with noop, its failing due to permission issues or trying to write files and configure devices. When `noop` is used, there shall be no changes made to the machine, while the configuration files or templates derived shall be output on the console. This is done so that the template/compatibility issues of the config.yaml could be validated on a given hardware without changing the system files or configuration.
(cherry picked from commit 2e60c77aee02d682028ff7795f5df1e9c9a0ae4e)
> noop: Run os-net-config without applying the changes

- os_net_config/dcb_config.py
- os_net_config/sriov_config.py
- os_net_config/tests/test_impl_ifcfg.py
- os_net_config/tests/test_impl_nmstate.py
- os_net_config/tests/test_objects.py
The unit testcases are failing with the error
```NameError: name 'noop' is not defined```
Invoked set_noop() in the setUp() routines of all the tests, so
that the global variable ```noop``` is defined and available to
the unit tests. os-net-config-sriov and os-net-config-dcb entry
points are updated as well.
(cherry picked from commit 7dc3da24f13da88de84c6d60683f5e69b32146c8)
> Fix test cases for noop

- os_net_config/cli.py
- os_net_config/common.py
- os_net_config/impl_ifcfg.py
- os_net_config/impl_nmstate.py
- os_net_config/objects.py
- os_net_config/tests/test_cli.py
- os_net_config/tests/test_impl_ifcfg.py
- os_net_config/tests/test_impl_nmstate.py
- os_net_config/tests/test_objects.py
- os_net_config/tests/test_utils.py
- os_net_config/utils.py
Presently the PCI address is read using ethtool command, when the device is bound with standard netdev driver. It is fetched from dpdk map when its bound with vfio-pci. The caller is expected to identify the device type and choose the appropriate function. The get_pci_address(interface_name) will now handle fetching the PCI address of the interface irrespective of the device types. In addition to that, now the PCI address of the SR-IOV VFs also could be fetched by passing the interface name in the format f"{pf_name}:{vfid}".
> utils: simplify get_pci_address()

- os_net_config/impl_nmstate.py
- os_net_config/objects.py
- os_net_config/tests/test_impl_nmstate.py
- os_net_config/utils.py
When nmstate provider is used for NIC partitioning, the dispatch scripts shall be used to setup the driverctl override for the VFs that shall be attached to the dpdk port. This will ensure that the persistence of the override is taken care during reboot scenarios.
(cherry picked from commit 4a1adaefffd021f3a433504e0cfa2f5f449c98d5)
> dpdk: Bind the VFs with the drivers using dispatcher scripts

- os_net_config/common.py
- os_net_config/objects.py
- os_net_config/tests/test_cli.py
- os_net_config/tests/test_impl_ifcfg.py
- os_net_config/tests/test_impl_nmstate.py
- os_net_config/tests/test_objects.py
- os_net_config/tests/test_utils.py
- os_net_config/utils.py
sriov: add pci address and mac address in sriov map
SR-IOV PF's pci address and mac address shall be stored
in the map, so that when the PF is attached to the guest, the
PF's details coud be read.
Signed-off-by: Karthik Sundaravel <ksundara@redhat.com>
> sriov: add pci address and mac address in sriov map

- os_net_config/impl_nmstate.py
- os_net_config/schema.yaml
- os_net_config/tests/test_impl_nmstate.py
this PR will allow to use 'self' str in next_hop inorder to route though the device.
{"ip_netmask": "0.0.0.0/0", "next_hop": "self" }  or "routes": [{"ip_netmask": "::/0", "next_hop": "self" }]
(cherry picked from commit 47a3903fbb0740b09fe8fc6ab898c45aeff9c7d0)
> route: adding the option to add route via next-hop-interface

- os_net_config/__init__.py
- os_net_config/cli.py
- os_net_config/common.py
- os_net_config/dcb_config.py
- os_net_config/impl_eni.py
- os_net_config/impl_ifcfg.py
- os_net_config/impl_nmstate.py
- os_net_config/objects.py
- os_net_config/sriov_bind_config.py
- os_net_config/sriov_config.py
- os_net_config/tests/test_utils.py
- os_net_config/utils.py
These below issues are addressed here
- The logging in nmstate provider is printing the data structures in json format which is not easy to read and decipher. These data structures are printed in yaml format for the ease of reading.
- Some of the logs are repeated at several levels leading to duplication of the logging.
- All the logs are done in same format.
Conflicts resolved in os_net_config/cli.py
- 'is_nmstate_available' function not present in stable/wallaby. So, skipped that function log message changes
(cherry picked from commit 7209726bfa384db47caee9895f65305b6a72683e)
> logs: make logging precise and readable

- os_net_config/dcb_config.py
This change introduces the 'is_dcbx_mstconfig_enabled' function, which verifies if DCBX mode is correctly enabled on Mellanox NICs using the 'mstconfig' tool. Based on this, we can check if mstconfig and mstfwreset needs to be done or not.
(cherry picked from commit ff88b85e9ec3cf191826e8c5f21b8d9f9a1aa46d)
> dcb: add function to verify DCBX mode config using mstconfig

- os_net_config/common.py
- os_net_config/tests/test_utils.py
Fix the typo in reading MAC address for SR-IOV PFs using _get_sriov_mac_address().
> utils: fix typo for mac address

- os_net_config/tests/test_utils.py
- os_net_config/utils.py
The parsing of the sriov_map added recently in _ordered_nics() created a regression. The pf dict is wrongly used instead of the pf["name"], which resulted in the regression.
> sriov: failure in parsing sriov_map

- os_net_config/cli.py
- os_net_config/common.py
- os_net_config/impl_ifcfg.py
- os_net_config/impl_nmstate.py
- os_net_config/objects.py
- os_net_config/tests/test_cli.py
- os_net_config/tests/test_impl_ifcfg.py
- os_net_config/tests/test_impl_nmstate.py
- os_net_config/tests/test_objects.py
- os_net_config/tests/test_utils.py
- os_net_config/utils.py
Presently the PCI address is read using ethtool command, when the device is bound with standard netdev driver. It is fetched from dpdk map when its bound with vfio-pci. The caller is expected to identify the device type and choose the appropriate function. The get_pci_address(interface_name) will now handle fetching the PCI address of the interface irrespective of the device types. In addition to that, now the PCI address of the SR-IOV VFs also could be fetched by passing the interface name in the format f"sriov:{pf_name}:{vfid}". With the usage of sysfs, the name of sriov vf is not required to fetch the pci address. This will be used in nic partitioning use cases when sriov_drivers_autoprobe is disabled.
(cherry picked from commit d268100293fb82e11597ff5945a01d6473b204a9)
> utils: simplify get_pci_address() implementation

- os_net_config/impl_nmstate.py
- os_net_config/tests/test_impl_nmstate.py
If the IP rules are not defined by NetworkManager, os-net-config will be unable to remove them, resulting in a Verification Error. With this pull request, os-net-config record rules set by os-net and will ignore other rules set on host
> iprules: ignore defined ip rules

- os_net_config/common.py
- os_net_config/impl_nmstate.py
- os_net_config/sriov_config.py
- os_net_config/tests/test_utils.py
- os_net_config/utils.py
sriov: Skip PF configuration when its attached to guest
In scenarios where the PF is attached to the guest, the PF device will not be visible in the hosts net subsystem. And if os-net-config is rerun in that scenario, the NIC mapping would fail. Checks shall be added so that the situation where the PF is attached to the guest is detected and handled.
> Pf given to guest

- os_net_config/schema.yaml
- os_net_config/tests/test_validator.py
The current route schema requires `next_hop` when `ip_netmask` is configured and `nexthop` when `destination` is configured. But since the schema validation is ignored until recently and the object parser parses both `nexthop` and `next_hop` alike, the schema validation failure for the same did not fail os-net-config. Now the schema for `route` object is modified to support both `nexthop` and `next_hop` and hence the schema validation will not fail on existing deployments for the same.
> schema: route schema shall support nexthop and next_hop

- os_net_config/common.py
- os_net_config/impl_nmstate.py
- os_net_config/sriov_config.py
- os_net_config/tests/test_utils.py
- os_net_config/utils.py
In scenarios where the PF is attached to the guest, the PF device will not be visible in the hosts net subsystem. And if os-net-config is rerun in that scenario, the NIC mapping would fail. Checks shall be added so that the situation where the PF is attached to the guest is detected and handled.
(cherry picked from commit 91659a82a823c67cfb090613fbf4e13d574bcce2)
> sriov: skip PF configuration when its attached to guest

- os_net_config/__init__.py
Verify file existence before attempting removal to prevent errors.
jira: https://github.com/os-net-config/os-net-config/pull/178
> ifcfg: verify file existence before removal

- os_net_config/impl_nmstate.py
The bind scripts used in network manager dispatcher fails to handle the scenario when the VFs are not bound with any driver. The path /sys/bus/pci/devices/$vf_pci_id/driver will not be present when the sriov_drivers_autoprobe is disabled. The same is handled with this patch.
> nmstate: bind scripts fail when drivers_autoprobe is disabled

- os_net_config/impl_ifcfg.py
- os_net_config/tests/test_impl_ifcfg.py
In ifcfg provider, the utils.diff() compares the content of the new ifcfg file and existing ifcfg file.
For OvS devices, there are fields like BOND_IFACES, OVS_EXTRA where the order of the entry doesn’t matter. The diff shall ignore the order of the entries for such fields.
Closes: https://issues.redhat.com/browse/OSPRH-13695
Signed-off-by: vcandapp <vcandapp@redhat.com>
(cherry picked from commit 39542dd46c04041a9f1317378045cc4e21723f71)
> bond: ignore order for dpdkbond

- os_net_config/common.py
- os_net_config/tests/test_cli.py
- os_net_config/tests/test_objects.py
- os_net_config/tests/test_sriov_bind_config.py
- os_net_config/tests/test_sriov_config.py
- os_net_config/tests/test_utils.py
The noop dry run attempts to write to the sriov map, which results in failure for non privileged users. The fix is to avoid writing to the map files during dry run.
> noop: fix noop run for nic partitioning use case

- os_net_config/tests/test_impl_nmstate.py
- os_net_config/tests/test_objects.py
- os_net_config/tests/test_sriov_config.py
The unit tests fails while accessing /var/lib/os-net-config/sriov_config.yaml. Also the temporary files corresponding to sriov_config.yaml, rep-link-name.sh 80-persistent-os-net-config.rules are removed during tearDown()
> sriov: sriov: unit tests fails while accessing sriov_config.py

- os_net_config/common.py
- os_net_config/objects.py
- os_net_config/tests/test_cli.py
sriov: Handle NIC partitioning while autoprobe is disabled
When drivers_autoprobe is disabled for sriov_pf, the VFs created
will not be bound with the required net drivers and hence those
VFs would not be listed in the /sys/class/net/<vf name>.
In order to make the NIC partitioning functional the required drivers
needs to be bounded with the VF.
> sriov: Handle NIC partitioning while autoprobe is disabled

- os_net_config/tests/test_impl_nmstate.py
- os_net_config/tests/test_objects.py
- os_net_config/tests/test_sriov_config.py
The unit tests fails while accessing /var/lib/os-net-config/sriov_config.yaml. Also the temporary files corresponding to sriov_config.yaml, rep-link-name.sh 80-persistent-os-net-config.rules are removed during tearDown()
(cherry picked from commit 0c3447cee32a4708fde78ba71f0c65ad51472b6d)
> sriov: unit tests fails while accessing sriov_config.yaml

- os_net_config/impl_ifcfg.py
- os_net_config/tests/test_impl_ifcfg.py
Stops removing NetworkManager connections from the ifcfg provider. The logic in the NetworkManager cleanup is too indiscriminate and can cause removal of connections that don't need to be removed, should not be removed, and/or can cause spurious errors. A follow-up patch will
ensure there are no conflicts in a safe way that allows for peaceful co-existence of network-scripts and nmstate.
Suggested-by: Karthik Sundaravel <ksundara@redhat.com>
Signed-off-by: Dan Sneddon <dsneddon@redhat.com>
Fixes:  https://issues.redhat.com/browse/OSPRH-15443
> cleanup: stop blindly removing nmconnection files

- os_net_config/sriov_config.py
The required driver for the VF shall be bound before applying the promisc settings. This is required to handle  NIC partitioning while sriov_drivers_autoprobe is disabled.
> sriov: driver binding for VF before enabling promisc

- os_net_config/common.py
- os_net_config/impl_ifcfg.py
- os_net_config/impl_nmstate.py
- os_net_config/objects.py
The vfid of sriov vf is used as a string and integer and this resulted in logging errors. Now %s is used as format specifier to handle all the usages.
> logs: remove logging errors for sriov vf

- os_net_config/impl_nmstate.py
- os_net_config/tests/test_impl_nmstate.py
When network_update is performed for ovs_bridge, we need to skip the verification of patch ports
Closes: https://issues.redhat.com/browse/OSPRH-17622
> nmstate: skip verification of patch ports

- os_net_config/cli.py
- os_net_config/common.py
- os_net_config/impl_nmstate.py
The cleanup actions cannot be allowed on ovs interfaces, ovs bridges, SR-IOV devices and other interfaces defined in config.yaml. If there is a real need to remove these interfaces it would be recommended to re-configure the system again instead of cleanup.
Closes: https://issues.redhat.com/browse/OSPRH-17034
(cherry picked from commit 805ec05f8553d5d3b19c839b507b4c0779c0d9cf)
> nmstate: avoid cleanup of ovs, sriov and other config.yaml interfaces

- os_net_config/utils.py
Start the sriov service in debug mode to enable logging
Closes: https://issues.redhat.com/browse/OSPRH-17313
(cherry picked from commit dabb392041f41fd0b29fd8975ca8fc04d69690fc)
> sriov: enable debug mode for sriov service

- os_net_config/common.py
- os_net_config/utils.py
Add utility methods to detach the dpdk ports from ovs and unset the
driver overrides configured for the dpdk ports.
> migrate: add utils to destroy dpdk ports

- os_net_config/utils.py
During migration from ifcfg to nmstate provider the config files sriov_config.yaml, dpdk_mapping.yaml, 70-os-net-config-sriov.rules shall be backed up.
> migrate: backup the dpdk,sriov map files

- check-commits
Enable AI assistance acknowledgment in commit messages by adding "Assisted-by" to the sanctioned trailer list.
Assisted-by: cursor/claude-4-sonnet
(cherry picked from commit 859ec18b60c73b2c1fe471a02904ac11fb61e8e4)
> check-commits: add assisted-by to allowed trailers

- doc/source/usage.rst
- os_net_config/cli.py
- os_net_config/tests/test_cli.py
cli: add ExitCode enum to replace magic numbers in return values
- Define ExitCode enum with SUCCESS (0), ERROR (1), FILES_CHANGED (2)
- Replace all numeric return statements with descriptive enum values
- Update comments and docstrings to reference enum names
- Improve code readability and maintainability by eliminating magic numbers
This makes the exit code semantics self-documenting and easier to understand
for developers working with the CLI module.
Signed-off-by: Karthik Sundaravel <ksundara@redhat.com>
> cli: add ExitCode enum to replace magic numbers in return values

- os_net_config/common.py
Added the gettimeofday() method, which could be used in timestamping the creation of backup files/folders.
> utils: add gettimeofday() for timestamping backup

- os_net_config/objects.py
- os_net_config/tests/test_objects.py
In nic partitioning case involving ovs_bond, the sriov vf map is not updated with the pci address of the VF. The pci address of the VF is now added.
(cherry picked from commit 84b705bd7dc9ecc2a93faa03f734aca308964a2f)
> ovs: add pci address of vf used as member of ovs_bond

- os_net_config/impl_nmstate.py
- os_net_config/tests/test_impl_nmstate.py
The `remove_config` feature needs the helper methods to fetch the pci address of the DPDK ports and the DPDK bonds. The pci address fetched could be later used in detaching it from the dpdk ports and unbind the same from vfio-pci driver. Since the `remove_config` feature could remove a dpdk interface which is not previously configured by os-net-config, the usage of dpdk map is avoided. The current interface states listed by `netinfo` is instead used in reading the PCI addresses.
> nmstate: add helpers to get pci address of DPDK ports / bonds

- os_net_config/cli.py
Changes are done to remove the redundant call to
common.reset_dcb_map() as already this would have
got called earlier.
> dcb: remove redundant call to reset_dcb_map

- os_net_config/cli.py
In get_iface_config() should do the schema validation as-is on the YAML data in user input. Schema checks for internal types like nic_mapping, persist_mapping  is not needed
> cli: schema validation is needed only for user input

- os_net_config/cli.py
Changes are done to show complete traceback in case the configuration fails
> cli: log full traceback on configuration failure

- os_net_config/impl_nmstate.py
- os_net_config/tests/test_impl_nmstate.py
- os_net_config/utils.py
This patch adds dispatcher script support for interfaces with static IPv6 addresses which sets the sysctl for keep_addr_on_down in order to have static IPv6 addresses act similar to static IPv4 addresses (interfaces keep their IP address when down or on reboot without requiring automatic configuration).
A follow-up patch will attempt to replicate this behavior for ifcfg files that have NM_CONTROLLED=yes, but that will require handling the dispatcher script fully within os-net-config without the benefit of native support for dispatcher script provided by nmstate.
> nmstate: keep_addr_on_down dispatcher script

- os_net_config/tests/test_impl_nmstate.py
- os_net_config/utils.py
The sysctl_path() needs to be stubbed for the unit tests to pass.
> nmstate: fix sysctl path for tests

- os_net_config/impl_ifcfg.py
- os_net_config/tests/test_impl_ifcfg.py
When using cloud-init generated ifcfg connections with nmstate provider, NetworkManager connection conflicts occurred due to stale connection cache. Adding nmcli connection reload after device removal ensures NetworkManager recognizes the updated network state, allowing mixed scenarios (cloud-init ifcfg + nmstate configuration) to work correctly.
> ifcfg: fix mixed provider compatibility with nmstate
